code: 'asmt'
name:
  default_value: sample
  key: assignemnt_name

description:
  default_value: sample description
  key: assignemnt_description

messages:
  - type: basic-lti-launch-request
    route:
      path: sample
      controller: sample
      action: launch
    parameters:
      - name: course_id
        variable: Course.id
      - name: first_name
        variable: Person.name
        required: true
      - name: xyzzy
        fixed: yzzyx